//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoVoyageV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssuranceAnnulation
    {
        public int IdAssuranceAnnulation { get; set; }
    
        public virtual Assurance Assurance { get; set; }
    }
}
