//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoVoyageV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination
    {
        public int IdDestination { get; set; }
        public string Continent { get; set; }
        public string Pays { get; set; }
        public string Région { get; set; }
        public string Description { get; set; }
    
        public virtual Voyage Voyage { get; set; }
    }
}
